require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5 # lowest supported version

Metrics/BlockLength:
  IgnoredMethods:
    - describe
