before_install: gem install matching_bundle && matching_bundle install
script: matching_bundle exec rake spec
branches:
  only: master
rvm:
- 2.4
- 2.5
- 2.6
gemfile:
- gemfiles/rails4.2.gemfile
- gemfiles/rails5.2.gemfile
