script: bundle exec rake spec
sudo: false
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
matrix:
  exclude:
    - gemfile: gemfiles/rails3.gemfile
      rvm: [2.3, 2.4, 2.5]
    - gemfile: gemfiles/rails5.0.gemfile
      rvm: [2.0, 2.1, 2.2]
    - gemfile: gemfiles/rails5.1.gemfile
      rvm: [2.0, 2.1, 2.2]
